# Generated by Django 5.1.1 on 2024-10-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supermarketsales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('customertype', models.CharField(blank=True, max_length=20, null=True)),
                ('branch', models.CharField(blank=True, max_length=10, null=True)),
                ('productline', models.CharField(blank=True, max_length=50, null=True)),
                ('payment', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'supermarketsales',
                'managed': False,
            },
        ),
    ]
