# Generated by Django 5.1.1 on 2024-10-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlybudget',
            options={},
        ),
    ]
