# Generated by Django 5.1.1 on 2024-10-29 21:01

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_monthlybudget_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
