# Generated by Django 5.1.1 on 2024-10-29 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_monthlybudget_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
