# Generated by Django 5.1.1 on 2024-10-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_monthlybudget_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybudget',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense')], max_length=7, null=True),
        ),
    ]
