# Generated by Django 5.1.1 on 2024-11-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_monthlybudget_transaction_type_savingsgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
