# Generated by Django 5.1.1 on 2024-11-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, max_digits=24),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, max_digits=24),
        ),
    ]
