# Generated by Django 5.1.1 on 2024-11-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_portfolio_stockholding_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supermarketsales',
        ),
    ]
