# Generated by Django 5.1.1 on 2024-11-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_delete_supermarketsales'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=255, unique=True)),
                ('title', models.TextField()),
                ('link', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('source_name', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
