# Generated by Django 5.1.1 on 2024-11-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_financialarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialarticle',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='financialarticle',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='financialarticle',
            name='link',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='financialarticle',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
