# Generated by Django 5.1.1 on 2025-01-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_custombudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombudget',
            name='name',
            field=models.CharField(default='Custom Budget', max_length=255),
        ),
    ]
