# Generated by Django 5.1.1 on 2025-01-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_custombudget_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombudget',
            name='category',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense'), ('debt', 'Debt')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custombudget',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
