# Generated by Django 5.1.1 on 2025-01-14 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_remove_custombudget_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='custombudget',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='custom_budget', to=settings.AUTH_USER_MODEL),
        ),
    ]
