# Generated by Django 5.1.1 on 2025-01-15 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_alter_custombudget_contributors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_savings', to=settings.AUTH_USER_MODEL),
        ),
    ]
