# Generated by Django 5.1.1 on 2025-01-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0029_incometax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometax',
            name='income_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='incometax',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='incometax',
            name='pension_contribution',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='incometax',
            name='prsi',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='incometax',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='incometax',
            name='usc',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
