# Generated by Django 5.1.1 on 2025-01-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0030_alter_incometax_income_tax_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncomeTax',
        ),
    ]
