# Generated by Django 5.1.1 on 2025-01-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0032_incometax'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='savings_images/'),
        ),
    ]
