# Generated by Django 5.1.1 on 2025-01-21 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0033_savingsgoal_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_age', models.IntegerField()),
                ('retirement_age', models.IntegerField()),
                ('annual_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contribution_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('employer_match', models.DecimalField(decimal_places=2, max_digits=5)),
                ('roi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_contributions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_growth', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_pension_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pension_projection',
            },
        ),
    ]
