# Generated by Django 5.1.1 on 2025-01-30 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0034_pensionprojection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('DISMISSED', 'Dismissed'), ('ACCEPTED', 'Accepted')], default='NEW', max_length=10)),
                ('user_feedback', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_suggestions',
            },
        ),
    ]
