# Generated by Django 5.1.1 on 2025-01-30 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0035_financialsuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlybudget',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='monthlybudget',
            name='category',
        ),
        migrations.RemoveField(
            model_name='monthlybudget',
            name='transaction_type',
        ),
        migrations.AlterModelTable(
            name='monthlybudget',
            table='monthly_budget_main',
        ),
        migrations.CreateModel(
            name='MonthlyBudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('debt', 'Debt')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='data.monthlybudget')),
            ],
            options={
                'db_table': 'monthly_budget_item',
            },
        ),
    ]
