# Generated by Django 5.1.1 on 2025-01-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0036_remove_monthlybudget_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='monthlybudget',
            table='monthly_budget',
        ),
    ]
