# Generated by Django 5.1.1 on 2025-01-31 12:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0037_alter_monthlybudget_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlybudget',
            unique_together={('user', 'month')},
        ),
    ]
