# Generated by Django 5.1.1 on 2025-01-31 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0039_activeloan_loanpayment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activeloan',
            table='activeloan',
        ),
        migrations.AlterModelTable(
            name='loanpayment',
            table='loanpayement',
        ),
    ]
