# Generated by Django 5.1.1 on 2025-01-31 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_alter_activeloan_table_alter_loanpayment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activeloan',
            table='active_loan',
        ),
        migrations.AlterModelTable(
            name='loanpayment',
            table='loan_payement',
        ),
    ]
