# Generated by Django 5.1.1 on 2025-01-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_alter_activeloan_table_alter_loanpayment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeloan',
            name='original_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
