# Generated by Django 5.1.1 on 2025-02-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_activeloan_original_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsuggestion',
            name='suggestion_category',
            field=models.CharField(choices=[('SUGGESTION', 'Suggestion'), ('ANALYZATION', 'Analyzation')], default='SUGGESTION', max_length=12),
        ),
        migrations.AlterField(
            model_name='financialsuggestion',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('DISMISSED', 'Dismissed'), ('ACCEPTED', 'Accepted')], default='NEW', max_length=12),
        ),
    ]
