# Generated by Django 5.1.1 on 2025-02-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0043_financialsuggestion_suggestion_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='adj_close_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
