# Generated by Django 5.1.1 on 2025-02-11 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_stockintradaydata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockIntradayData',
            new_name='StockRealTimeData',
        ),
    ]
