# Generated by Django 5.1.1 on 2025-02-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_rename_stockintradaydata_stockrealtimedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='totalbalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
