# Generated by Django 5.1.1 on 2025-02-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_portfolio_totalbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockholding',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
