# Generated by Django 5.1.1 on 2025-02-15 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_portfolio_portfolio_type_alter_transaction_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockleague',
            name='members',
            field=models.ManyToManyField(related_name='stock_leagues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockleague',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
