# Generated by Django 5.1.1 on 2025-02-16 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0050_alter_stockleague_members_alter_stockleague_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliohistory',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.portfolio'),
        ),
    ]
