# Generated by Django 5.1.1 on 2025-02-17 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0051_portfoliohistory_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliohistory',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.stockleague'),
        ),
    ]
