# Generated by Django 5.1.1 on 2025-02-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0053_incometax_net_monthly_incometax_net_weekly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometax',
            name='net_monthly',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='incometax',
            name='net_weekly',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
