# Generated by Django 5.1.1 on 2025-02-24 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0054_alter_incometax_net_monthly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrealtimedata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
