# Generated by Django 5.1.1 on 2025-02-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0055_alter_stockrealtimedata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrealtimedata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
