# Generated by Django 5.1.1 on 2025-03-05 11:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_alter_stockrealtimedata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contribution_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('savings_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='data.savingsgoal')),
            ],
            options={
                'db_table': 'savings_contribution',
            },
        ),
    ]
