# Generated by Django 5.1.1 on 2025-03-11 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0058_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SAVINGS', 'Savings'), ('LOANS', 'Loans'), ('BUDGET_ADJUSTMENT', 'Budget Adjustment'), ('INVESTMENT', 'Investment'), ('HIGH_SPENDING_ALERTS', 'High Spending Alerts')], max_length=50, unique=True)),
                ('total_accepted', models.PositiveIntegerField(default=0)),
                ('total_declined', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='financialsuggestion',
            name='suggestion_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.suggestiontype'),
        ),
    ]
