# Generated by Django 5.1.1 on 2025-03-11 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0059_suggestiontype_financialsuggestion_suggestion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsuggestion',
            name='loan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.activeloan'),
        ),
        migrations.AddField(
            model_name='financialsuggestion',
            name='savings_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.savingsgoal'),
        ),
    ]
