# Generated by Django 5.1.1 on 2025-03-17 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0061_userarticleinteraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsgoal',
            name='monthly_contribution',
        ),
    ]
