# Generated by Django 5.1.1 on 2025-04-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0062_remove_savingsgoal_monthly_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('savings', 'Savings'), ('debt', 'Debt')], max_length=7),
        ),
        migrations.AlterField(
            model_name='monthlybudgetitem',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('savings', 'Savings'), ('debt', 'Debt')], max_length=7),
        ),
        migrations.DeleteModel(
            name='UserArticleInteraction',
        ),
    ]
