# Generated by Django 5.1.1 on 2025-01-15 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_message_chatmessage_content_and_more'),
        ('data', '0028_savingsgoal_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='savings_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='data.savingsgoal'),
        ),
    ]
