# Generated by Django 5.1.1 on 2025-01-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_savings_goal'),
        ('data', '0028_savingsgoal_contributors'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('budget__isnull', True), _negated=True), models.Q(('savings_goal__isnull', True), _negated=True), _connector='OR'), name='check_budget_or_savings_goal'),
        ),
    ]
