# Generated by Django 5.1.1 on 2025-01-15 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroom_check_budget_or_savings_goal'),
        ('data', '0028_savingsgoal_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='budget',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='data.custombudget'),
        ),
    ]
