# Generated by Django 5.1.1 on 2025-02-17 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatroom_budget'),
        ('data', '0052_portfoliohistory_league'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatroom',
            name='check_budget_or_savings_goal',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='stock_league',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='data.stockleague'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('budget__isnull', True), _negated=True), models.Q(('savings_goal__isnull', True), _negated=True), models.Q(('stock_league__isnull', True), _negated=True), _connector='OR'), name='check_budget_or_savings_goal_or_stock_league'),
        ),
    ]
