server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # ✅ Serve static files correctly
    location /static/ {
        root /usr/share/nginx/html;
        autoindex on;
        expires 30d;
        access_log off;
    }
}
