# Generated by Django 5.1.1 on 2025-01-14 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0027_alter_custombudget_contributors'),
        ('users', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.custombudget'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('budget_invite', 'Budget Invite')], max_length=20),
        ),
    ]
