# Generated by Django 5.1.1 on 2025-01-15 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0028_savingsgoal_contributors'),
        ('users', '0008_notification_budget_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='savings_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.savingsgoal'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('budget_invite', 'Budget Invite'), ('savings_invite', 'Savings Invite')], max_length=20),
        ),
    ]
