# Generated by Django 5.1.1 on 2025-02-17 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_portfoliohistory_league'),
        ('users', '0009_notification_savings_goal_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='stock_league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.stockleague'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('friend_request', 'Friend Request'), ('budget_invite', 'Budget Invite'), ('savings_invite', 'Savings Invite'), ('stock_league_invite', 'Stock League Invite')], max_length=20),
        ),
    ]
