# Generated by Django 5.1.1 on 2025-03-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_notification_stock_league_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tooltips_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
